### ISSUE TITLE
開発環境をdevcontainerで立てやすくする

### ISSUE THREAD

**Issue by tuna2134** [SakuraProject/sakura-bot#103]

**Comment by tuna2134** [comment]
https://code.visualstudio.com/docs/devcontainers/containers

**Comment by tuna2134** [comment]
@yaakiyu 必要なvscodeライブラリどうする？

**Comment by yaakiyu** [comment]
読んでもよくわからなかったので...()
質問です
* DevContainerって何ですか
* (文章読んでみたけど)Dockerコンテナって何ですか
* (そういえばまず)コンテナって何ですか
* 利点は何ですか(おそらく「環境構築がしやすい」だろうけど、具体的にどういうふうにやりやすくなるのか知りたい)
* 導入に必要なのって何ですか
* vscodeライブラリって何ですか
多いけどごめんね()

**Comment by yaakiyu** [comment]
「コンテナ」から調べようと思ったけどまず「仮想化」がわからなかった；；

**Comment by tuna2134** [comment]
Devcontainerに関してはビルド実行すれば、自動的に開発環境を立ててくれる
Dockerコンテナは環境を隔離できる
コンテナはDockerコンテナと同じだと思えば
利点はボタン一つでMySQLサーバーとか自動的に立ててくれる
vscodeライブラリ=vscode拡張機能って思ってくれればいい

**Comment by tuna2134** [comment]
仮想化はつまり環境をOSレベルで隔離する

**Comment by yaakiyu** [comment]
なるほど
何となくわかった

**Comment by yaakiyu** [comment]
色々みて思ったけど
自分の環境にdockerを入れることができない(アプリインストールを親に禁止されてる)から
これもまた「進めるなら勝手に進めてくれ」案件になるんだよな

**Comment by tuna2134** [comment]
github codespacesでも可能

**Comment by tuna2134** [comment]
できた
Codespaces作成時に自動的に構築してくれる
