### ISSUE TITLE
SQLAlchemy導入について

### ISSUE THREAD

**Issue by kousakirai** [SakuraProject/sakura-bot#104]
#99 より移動

**Comment by yaakiyu** [comment]
SQLAlchemyの仕組みを見る限り僕は悪い気はしない。
ネイティブでもPythonicでも操作できるから、好きな方で使える。
ただSakuraBotはテーブル数がかなり多くて、主キーがdiscordで決められたIDだからそれぞれのテーブルが独立している(だいたいcog1個につきテーブル1個)から利点が薄いような気もする。

**Comment by tuna2134** [comment]
それは思った
というかコードが長くなる可能性があるのが心配、、、

**Comment by yaakiyu** [comment]
提案者不在によりclose
