### ISSUE TITLE
Global Chatが接続したはずなのに機能しない

### ISSUE THREAD

**Issue by HardSmoothy** [SakuraProject/sakura-bot#108]
タイトルの通りです

再現：
①sk!gc createまたはスラッシュコマンドでグローバルチャットを生成
②メッセージを送信
③ほかのサーバー(私の場合はSakura projectサーバー)で転送されていないことが確認可能

補足：
このバグは、お問い合わせにあったものを実験鯖で検証し、Githubに再投稿したものです。
元投稿=> https://discord.com/channels/961521739748212776/1059108094728224838

**Comment by yaakiyu** [comment]
修正。
