### ISSUE TITLE
音楽再生で停止・再開を複数鯖で行うと秒数が狂う

### ISSUE THREAD

**Issue by yaakiyu** [SakuraProject/sakura-bot#109]
最後に停止・再開コマンドを実行したサーバーによってCogの`self.stopt`や`self.start`が上書きされるため、`sk!nowplaying`の秒数が狂う。

**Comment by ysmreg** [comment]
これはstartとかを辞書にしてサーバーごとに違う内容を保存できるようにすれば良さそう
