### ISSUE TITLE
helpコマンドの拡張

### ISSUE THREAD

**Issue by yaakiyu** [SakuraProject/sakura-bot#111]
* [ ] コマンド検索を、全文から・エイリアスから探せるようにする。
* [ ] コマンド名(もしくはエイリアス)で見つからなかったら、レーベンシュタイン距離かなんかを使って検索を行う。[rapidfuzzっていうライブラリ](https://qiita.com/fujine/items/b7189c4a55da33f821e3)があるらしいのでそれを使いたい。
* [ ] 検索結果があったらSelectにしてhelpを見られるようにする。
* [x] とりあえずカテゴリ表示のコマンドのところに`これ`つける。

**Comment by tuna2134** [comment]
正直これなくてもいいような気がする
スラッシュコマンド一本にして

**Comment by yaakiyu** [comment]
スラコマのみは嫌です

**Comment by tuna2134** [comment]
じゃあ、SakuraProjectでどうぞ
