### ISSUE TITLE
Sakura Point

### ISSUE THREAD

**Issue by yaakiyu** [SakuraProject/sakura-bot#51]
僕がsakurabotで一番作りたいシステム。

# 概要

sakurabotの利用や宣伝でポイントがもらえる。
SakuraBotのいくつかの機能でPointを使う。
つまりポイントはすべて架空のものであり、完全無料。

# 詳細

SakuraBotの宣伝(Botのリンクか公式サーバーのリンクがあるメッセージを送信すること)1回につき1000pointもらえる。
※ 宣伝でのポイント付与はサーバーごとに1時間のクールダウンあり
1回コマンドを使うと10ポイントもらえる。

使用方法については考え中(一応何個か思いついてるけどまだ具体的なものになっていない)

**Comment by ysmreg** [comment]
いいね、その機能

**Comment by yaakiyu** [comment]
宣伝時のポイント付与は作成した。

**Comment by yaakiyu** [comment]
SakuraPointの活用例、新たに作りたい新機能たちとも絡めながらたくさん考えた。

# 使いかた
Sakurabotの中のゲームで使う。(ネーミングは適当、それぞれの機能についてはあとでissue出す)
* Sakura RPG
* Sakura Typing
* Sakura Books ... 公式小説1話10point、個人小説1話30point、自分で作品を出すときは100point消費、買われた数に応じて報酬あり
* Sakura Ad ... 1回の広告で25pointもらう、広告チャンネルでは「見た」人が50point、見させた人は見るたびに5pointもらう、広告出すのに300 + (文字数 / 10) point (2000文字まで)

**Comment by yaakiyu** [comment]
とりあえず基本的な部分の実装は終わったのでclose
