### ISSUE TITLE
カスタムprefix

### ISSUE THREAD

**Issue by yaakiyu** [SakuraProject/sakura-bot#62]
サーバー・ユーザー別に使えるようにする。
デフォルトも`sk!`だけでなくさまざまな種類用意する。
(ちなみにこれを実装すると今のhelpは壊れる。EVALの中に`bot.command_prefix`を使っているから。)

**Comment by yaakiyu** [comment]
helpを修正したので実装可能になった。

**Comment by kousakirai** [comment]
テスト勉強＆課題粉砕の息抜きにコレやるか
