### ISSUE TITLE
優先事項

### ISSUE THREAD

**Issue by tuna2134** [SakuraProject/sakura-bot#65]
- [ ] スパゲティーコード(flake8つかって)を解く
- [ ] コードの効率化

**Comment by yaakiyu** [comment]
#54 を参照して、
書き直しが終わったものからチェック入れてほしい。

**Comment by tuna2134** [comment]
ちなみに機能を新しく作るのはなしね

**Comment by yaakiyu** [comment]
作りたい(
僕のスタンスは「自分のやりたいことを自由にやればいいよー」だから
あんまり人に強制させたくないし、生産性下がるのも嫌だしなぁと思って

**Comment by tuna2134** [comment]
> 作りたい(
> 僕のスタンスは「自分のやりたいことを自由にやればいいよー」だから
> あんまり人に強制させたくないし、生産性下がるのも嫌だしなぁと思って

わかるけど、変なコードを書きまくられて仕事を増やすのが嫌だ()

**Comment by yaakiyu** [comment]
「仕事」って()
こっちは趣味とかそういう範囲でやってるから
僕が全部書き直せばいいでしょ(知らんけど)
