### ISSUE TITLE
Docker移行が放置されてる件

### ISSUE THREAD

**Issue by kousakirai** [SakuraProject/sakura-bot#74]
対応するならするではよやってほしいし時間かかるってわかってるならわざわざmainブランチにぶち込むな定期
頼むから後続の開発者が手を出せんくなるからmainブランチに加えた変更を途中放棄しないでくれ

**Comment by tuna2134** [comment]
今テスト期間中
察してくれ

**Comment by kousakirai** [comment]
それならなおさらmainブランチに入れるなよ。俺今環境構築しようと思ったら書きかけであろうDockerfileのせいで積んでるんだが

**Comment by tuna2134** [comment]
ん？
k8s使う前提でPR作って、それをマージした。
だけどゴタゴタで変えないといかんから、、、

**Comment by kousakirai** [comment]
そもそも問題なく動くか検証してないものをmainに入れんなよ...

**Comment by tuna2134** [comment]
検証したよ

**Comment by tuna2134** [comment]
Minikubeでな？

**Comment by kousakirai** [comment]
いやいや、されてないでしょ。実際メモリ不足でマシン死んでたし

**Comment by kousakirai** [comment]
俺が言ってんのは実機環境で動くかどうかっていうのを検証しろよってことだよ

**Comment by tuna2134** [comment]
検証したよ

**Comment by tuna2134** [comment]
とっくの昔にな？
minikube startでk8sを動かしたけど、

**Comment by tuna2134** [comment]
予想外だったからね、、、
docker build -t sakurabot.
docker run sakurabot
で試してみて

**Comment by kousakirai** [comment]
いやだからさぁ...人の話聞いてる？マージする前に実機環境で動作に支障なく動くかどうかを検証してくれって言ってんだよ。
ローカル検証したって実機で動かんなんてことざらにあるのはわかってるやろ...

**Comment by tuna2134** [comment]
いや
普通にやっていて、それで死んだらそれこそどうなん？

**Comment by kousakirai** [comment]
普通にやっててってどういうこと？頼むから理解してる前提で喋るのをやめてくれ。その文章だと君が何を指してるかすら理解ができん。

**Comment by tuna2134** [comment]
それぐらい考えてくれ
実機環境でテストするだろ？
それで死んだら、、、変わらんやん

**Comment by tuna2134** [comment]
あとpipenvで今のところ動くはずだからそれでやってくれ

**Comment by kousakirai** [comment]
何を言ってんのかようわからんが、実機で動くかわからないものを自分のローカル環境で動いたからってmainブランチにPRして実際メモリ不足で鯖落としてるのは十分害悪行為やぞ。mainブランチにPRする前にk8sがどれぐらいのメモリを消費して、鯖側のメモリのサイズを把握する必要はあったんやない？

**Comment by tuna2134** [comment]
鯖側のメモリーを把握するのは確かにすべきだったと思うが、そこまで少ないとは思わなかった。

**Comment by kousakirai** [comment]
まあもうこの話はいいや。Docker対応は俺が引継ぎするわ。幸いしばらく時間あるから動かせるレベルにはできそう。
ただ少し気になったのがyaakiyuの環境ってdocker動かせるんか？
@yaakiyu

**Comment by tuna2134** [comment]
> まあもうこの話はいいや。Docker対応は俺が引継ぎするわ。幸いしばらく時間あるから動かせるレベルにはできそう。
> ただ少し気になったのがyaakiyuの環境ってdocker動かせるんか？
> @yaakiyu

もうめんどいから削除した

**Comment by kousakirai** [comment]
dockerはあったほうが俺的にも開発楽にできるからどちらにせよやるのはやるよ。

**Comment by tuna2134** [comment]
開発環境向けで頼んだ

**Comment by yaakiyu** [comment]
僕dockerの使い方わからんからこのissue丸投げなんだけど
どうしようかな

**Comment by yaakiyu** [comment]
ま、よくわからんから引き続き丸投げで(

**Comment by ysmreg** [comment]
cudaはなくても動作しますがtorchが必要なのは機械学習させたpthをつかって読み上げさせようとしたためです。cuda がない場合はCpuで音声合成されます

**Comment by tuna2134** [comment]
PyTorch自体デカすぎる

**Comment by ysmreg** [comment]
確かにpytorchは容量大きすぎますね()

**Comment by yaakiyu** [comment]
完了。
