### ISSUE TITLE
新規で開発に参加することのコストについて

### ISSUE THREAD

**Issue by kousakirai** [SakuraProject/sakura-bot#75]
今暇だから開発やろうと思ったんだけどこれちょっと始めるのきつくね？
手直しで.envにstripekeyとかtwitterapiが代入されてなかったらその機能がロードされないようにする仕組みでも作るわ
流石に全部揃えんのはきつい...

**Comment by yaakiyu** [comment]
KeyErrorが出るんだけど
エラーが出力されて次のcog読みに行くようになってるので
無視して構わないよ

**Comment by kousakirai** [comment]
あ、そうなってんのね。了解した
