### ISSUE TITLE
SakuraBotのYouTube再生機能について

### ISSUE THREAD

**Issue by ysmreg** [SakuraProject/sakura-bot#76]
discordによりYouTubeを再生するbotが制限されつつあります。現時点での導入サーバー数が66になっていて認証も近づいています。そこでYouTubeの再生機能をどうするかという問題です。
案1.SakuraPluginというものを作りyoutubeプラグインをインストールしたサーバーでのみ再生できるようにする(SakuraPointでプラグイン購入する仕組みでもあり)

案2.認証時だけ実機環境から削除する(認証後再追加)

案3.YouTubeの音楽を再生してるのを隠す(他のBotを参考にした)再生時にタイトルにつけるリンクをyoutubeの時のみ廃止にするなど

案3.youtube再生機能の現状維持

●他にも案を募集します

**Comment by yaakiyu** [comment]
案2推奨

**Comment by tuna2134** [comment]
そのあと、認証取り消される可能性あるので、廃止の方向を推奨

**Comment by ysmreg** [comment]
確かに認証後に認証取り消しされる可能性はある。最初は2か1がいいかなって思ってたけどYouTube再生機能のbotが消され始めたら廃止も考えないといけなくなるかもですね

**Comment by ysmreg** [comment]
メリットとデメリットを考えてみました
案1.
メリット
●案2の様にyoutubeを認証の時に廃止してその後プラグイン形式で提供した場合案2より認証を取り消される可能性が低い
●いろいろな機能にプラグイン形式で追加機能を作れたり、SakuraRPGのアイテムなどで隠しプラグインを登場させたり出来そう

デメリット
●認証が取り消しされるかもしれない
●プラグイン用の関数が増えたりする

案2
メリット
●認証前と変わらず音楽再生が使える
●手間があまりかからない

デメリット
●認証が取り消される可能性があります
●どのサーバーでも再生出来るためdiscordに確認される可能性が高い

案3
メリット
●認証期間中もyoutubeを再生出来る
●手間があまりかからない

デメリット
●気づかれたら認証が消される可能性があります

案4
メリット
●特に変更することがない

デメリット
●認証されない可能性がある

案5(youtube再生を廃止)
メリット
●認証を取り消しされる可能性が一番低い

デメリット
●音楽再生を目的とした利用者に選ばれにくくなる

**Comment by ysmreg** [comment]
@yaakiyu youtube再生するのをニコニコ動画にも置き換えできそうだけどどうしますか?

**Comment by yaakiyu** [comment]
youtube以外は続行してもいいんじゃないかな

**Comment by yaakiyu** [comment]
youtubeのリンク投げられたら「Watch Togetherをご利用ください。」って言えばいい

**Comment by ysmreg** [comment]
youtubeを消して他のをそのままにしたPR出しました

**Comment by tuna2134** [comment]
ミスった

**Comment by yaakiyu** [comment]
プラグイン自体は完成したのでclose
