### ISSUE TITLE
PyQRcodeのせいでpipenv installができない

### ISSUE THREAD

**Issue by kousakirai** [SakuraProject/sakura-bot#98]
pipfile.lockでビルド時に失敗するっぽい。多分こいつが古いせいで3.10.8で使えない説がある

**Comment by kousakirai** [comment]
https://github.com/lincolnloop/python-qrcode
こっちのライブラリは最近も更新されてるみたいだからこっちに乗り換えたほうが良いのではと個人的に思ってる

**Comment by kousakirai** [comment]
と言うか乗り換え作業しますわ。ついでにqrの実装部分も更新する

**Comment by yaakiyu** [comment]
あー
なるほど
ありがとう

**Comment by kousakirai** [comment]
途中経過報告：python-qrcodeで出力されたPILImageをbytesに変換すると何故か中身が消える。原因知ってるやついたら教えてクレメンス

**Comment by ysmreg** [comment]
import io
を追加して
```
qrbyte = io.BytesIO()
pilimage.save(qrbyte, format='PNG')
qrbyte = qrbyte.getvalue()

```
みたいにすればできるかもです

**Comment by kousakirai** [comment]
すでに試してたんだけど駄目だったんだよなぁ...
なんかsave関数を通すと駄目っぽい

**Comment by yaakiyu** [comment]
save関数通さずに直接`discord.File()`に渡せば?

**Comment by kousakirai** [comment]
多分無理だと思われるぞ。discord.File関数通してやろうとしてみたけどPILImageからbytesへの変換が必須だった。

**Comment by yaakiyu** [comment]
色々ソースコード見てきた。PILImageってクラス、独自実装だったのね...
```python
import io, qrcode

qr = qrcode.make("...")
qrbyte = io.BytesIO()
qr._img.save(qrbyte, format='PNG')  # _img属性にpil.Image.Imageクラスが入ってる
```

**Comment by kousakirai** [comment]
独自実装ちゃうで。PILの中にあるやつやで

**Comment by yaakiyu** [comment]
e
```
Or in Python, use the make shortcut function:

import qrcode
img = qrcode.make('Some data here')
type(img)  # qrcode.image.pil.PilImage
img.save("some_file.png")
``` [気のせいか...?](https://github.com/lincolnloop/python-qrcode#usage)

**Comment by kousakirai** [comment]
すまん違うわ独自実装だ

**Comment by yaakiyu** [comment]
でも見る限り独自実装の`save`関数でも問題はなさそうなんだよな...

**Comment by kousakirai** [comment]
何故かsaveすると中身が消滅する。俺の環境だけかもしれんから一回yaakiyuの手元の環境で試せそうなら試してみてほしい

**Comment by yaakiyu** [comment]
[ちゃんと生成されたよー](https://github.com/SakuraProject/sakura-bot/commit/9fd7fcd16d2f349a21b768756d7314459cadef3b)

**Comment by kousakirai** [comment]
メモリ上に書き出せる？BytesIOで。

**Comment by tasuren** [comment]
自分できたよ。

**Comment by kousakirai** [comment]
じゃあおま環かぁ...

**Comment by tasuren** [comment]
いや、まだわからん。どういうコードか見てないから。

**Comment by yaakiyu** [comment]
ってかたまにtasurenがひょこっと出てくるの面白い

**Comment by kousakirai** [comment]
```python
@qr.command(description="QRコードをテキストから生成します")
async def make(self, ctx: commands.Context, text: str):
    stream = BytesIO()
    img = qrcode.make(text)
    img.save(stream, "PNG")
    stream.seek(0)
    byte_img = stream.getvalue()
    print(type(byte_img))
    stream.close()
    file = discord.File(fp=byte_img)
    await ctx.reply(file=file)
```
ワイのローカルで動かしてるやつ

**Comment by tasuren** [comment]
本当に空になるの？

**Comment by yaakiyu** [comment]
`discord.File`に渡すのに`getvalue`をする必要なくね?
`bytes`に変換しちゃうと相対パスとして認識されるはず。

**Comment by tasuren** [comment]
`print(byte_img)`ってやれば何かしら表示されるはず。

**Comment by kousakirai** [comment]
それで返ってきたのが`b''`

**Comment by tasuren** [comment]
うぇ
自分のTermuxでやったらできたんだけどね。

**Comment by kousakirai** [comment]
俺もコンソール上でやる分には普通に行けるんよ。でもPythonでいざ動かそうとしたらダメになる
subprocess通してやるかなぁ...

**Comment by kousakirai** [comment]
画像生成自体はうまく行ってるけどそれをいざBytesIOに渡そうとすると事故るな。

**Comment by kousakirai** [comment]
seek忘れじゃねぇかこんちくしょう

**Comment by yaakiyu** [comment]
修正済み。
