### ISSUE TITLE
ログが分かりづらい

### ISSUE THREAD

**Issue by kousakirai** [SakuraProject/sakura-bot#99]
起動時に流れてるけどprintを使うのかloggingを使うのかどっちなのかわからんから統一してもろて

**Comment by kousakirai** [comment]
あと各Cogの読み込み完了のログをすべて消して
All cogs loaded!なりのログにまとめてもいいんじゃないだろうか

**Comment by yaakiyu** [comment]
デバッガー側のこと全然考えずに開発進めてたからなぁ...(
僕が作るときはloggingの方にしてるけど、printが残ってるのは古い残骸だな
ただ僕logging詳しくないのであんまりやる気が...((
各Cogでログ出してるのはなんかあった時のためだけど
よく考えると要らんかもな
どうにかしないと

あと、mysqlの`Table already exists`みたいなエラーが大量に流れるんだけど
何とかその表示消せないかな

**Comment by kousakirai** [comment]
Loggingに関しては昔触ってたからQRの問題解決次第やる。
mysqlも、独自のツールをやめてSQLAlchemyを採用してぇなぁって個人的にちょっと思ってたからyaakiyuがGOサイン出してくれるなら作業するよ
https://qiita.com/arkuchy/items/75799665acd09520bed2

**Comment by yaakiyu** [comment]
SQLAlchemyね...
触ったことないからあんまわからんけど
できるのであればやっていいよ

**Comment by kousakirai** [comment]
SQLAlchemyの移行作業はぼちぼちやるわ。
とりあえずlogging周りの作業は終わったよ。

**Comment by tuna2134** [comment]
SQL言語学んでくださいな

**Comment by kousakirai** [comment]
> SQLAlchemyは細かいところができないので反対する

細かいこととは？抽象的な言い方じゃなくて具体的な言い方で反論してくださいな。
仮に生のSQL文を実行できないことを指してるなら
https://www.sukerou.com/2019/04/sqlalchemysqlsql.html
この記事に方法が乗ってるのでSQLAlchemyを使用することを反対する理由にはならないが。

**Comment by tuna2134** [comment]
一つに統一したい無理

**Comment by tuna2134** [comment]
さらにif文とか向こうでランダム数字列を作成することもできない

**Comment by tuna2134** [comment]
しかも大体の人は今になれているから変える必要がない

**Comment by tuna2134** [comment]
あとここで話すことではない

**Comment by kousakirai** [comment]
> さらにif文とか向こうでランダム数字列を作成することもできない

人の文章ぐらいちゃんと読めよ。SQL文実行可能って書いてんだろうが。sql.alchemy.sql.text関数にSQL文流し込んでexecute関数に投げれば実行できる。



> しかも大体の人は今になれているから変える必要がない

慣れてる=使い易いではないだろ。はっきり言うけど今のこの状態まじで使いづらい。どこでどんなテーブルが発行されていてどんな処理をしているのかの把握が死ぬほど面倒。SQLAlchemyを使えばmodelを定義してそれに従ってテーブルが作成されるようにできる。

気に入らんのならまずSQLAlchemyでできないことを根拠ありきで否定しろよ。自分の思い込みや正しくない知識で物語るなや。〇〇だから～って言いてぇなら人が納得するような根拠を出せや。議論をする前にシャットアウトするのはただの害悪やぞ。あと人の質問にまともに答えろ。こっちは「細かいことって何？具体的にあげて」って聞いてんのに「一つに統合したい無理」って答えになってねぇんだよ。疑問詞で聞いてんのにYesかNoで答える日本人かよ。

> あとここで話すことではない

それはそうやな。issueを別で建てておくことにする。

**Comment by tuna2134** [comment]
それはお前だけだろ

**Comment by tuna2134** [comment]
使いずらいと思ったのは、全員にアンケート取ってから言えよ

**Comment by tuna2134** [comment]
しかもあれ非同期がない時点で終わっている。導入しない方がいい

**Comment by tuna2134** [comment]
少なくとも今の状態をわざわざ手間暇かけてかくひつようがない

**Comment by tuna2134** [comment]
> 気に入らんのならまずSQLAlchemyでできないことを根拠ありきで否定しろよ。自分の思い込みや正しくない知識で物語るなや。〇〇だから～って言いてぇなら人が納得するような根拠を出せや。議論をする前にシャットアウトするのはただの害悪やぞ。あと人の質問にまともに答えろ。こっちは「細かいことって何？具体的にあげて」って聞いてんのに「一つに統合したい無理」って答えになってねぇんだよ。疑問詞で聞いてんのにYesかNoで答える日本人かよ。
暴言吐くぐらいならやめたら？

**Comment by tuna2134** [comment]
別の言い方があるはず

**Comment by kousakirai** [comment]
> 使いずらいと思ったのは、全員にアンケート取ってから言えよ

はいはいｗわーったから出してやるよ。


> しかもあれ非同期がない時点で終わっている。導入しない方がいい

まじでロクに調べてねぇのな。aiomysqlをエンジンに使えば非同期使えるんだよ。


> 別の言い方があるはず

いい加減てめぇのその態度に苛つきが限界なんだわ。

**Comment by tuna2134** [comment]
じゃあやめろよ

**Comment by kousakirai** [comment]
そうかい。ならやめてやるわ。くそったれが。じゃあな。
yaakiyu俺のコントリまとめて解除しといて。俺がやることはもうないみたいや。

**Comment by tuna2134** [comment]
僕の言い方が少し悪かった。
で、僕の考えを聞いて欲しい。

SQLAlchemyに対する考え: ORMLibraryはたしかに楽なのは認める。だけどさらに高度なことをする際にexecuteとか混じって、途中でこれ何のために作ったのかがわからなくなって、最終的にダメなコードができるのが恐れている。しかも従来のやり方から異なるやり方にすると僕としてもすぐには適応できない
それと尖った言い方はやめてほしい

何か反論があれば、お願いします。

**Comment by yaakiyu** [comment]
うーん
なんで自分がいない間にこんなことになるんだ...
一方的にやめる話されても残されて困るのこっちなんだが...
SQLAlchemyの話は確かにここだとトピ違いだな
#104 行こう
